name: deploy
on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Configure gcloud
              id: 'auth'
              uses: 'google-github-actions/auth@v1'
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Deploy API
              uses: google-github-actions/deploy-cloudrun@v1
              with:
                  service: ${{secrets.GOOGLE_CLOUD_RUN_SERVICE}}
                  source: '.'
